### ISSUE TITLE
_handle_function trigger problem

### ISSUE THREAD

**Issue by Icegrave0391** [Pamplemousse/bits_of_static_binary_analysis#2]
Hi! I tried to reproduce RDA analysis, however, it seems that something wrong happened to `_handle_function` at `angr.analyses.reaching_definitions.engine_vex`:

at `engine_vex.py` line 576- line 583:
```
        # direct calls
        ext_func_name = None
        if not self.project.loader.main_object.contains_addr(func_addr_int):
            is_internal = False
            symbol = self.project.loader.find_symbol(func_addr_int)
            if symbol is not None:
                ext_func_name = symbol.name
        else:
            is_internal = True
```

It seems that engineVex tries to recognize ext_func via `main_object.contains_addr`, and tries to find that symbol. However, in my case:
![image](https://user-images.githubusercontent.com/31272993/111592258-8904ba80-8803-11eb-94cc-6a634ffd107e.png)
The external function `fputs` has been recognized as an internal function... Meanwhile, it's symbol could not be resolved... I wonder why is that happened?

**Comment by Pamplemousse** [comment]
Hi @Icegrave0391,
This seems to be a `angr` specific problem, so it would be more adequate to either: 1. Ask for help on [their slack](https://angr.slack.com/), 2. Raise an issue directly on [their GH repo](https://github.com/angr/angr/issues/new/choose).
Good luck!
