### ISSUE TITLE
Different Results

### ISSUE THREAD

**Issue by robe1221** [Pamplemousse/bits_of_static_binary_analysis#4]
On line 28 of the 01_command_line_injection_RDA_on_check.py file, the observed results in your video show regDefs, stackDefs, and memDefs.  However, when I run this example, up to that point on my own machine, I only see tmpDefs.  Is there code you are leaving out because it is your research or proprietary?  Or has the ANGR API changed for the RDA, which I can ask on the ANGR channels?

https://github.com/Pamplemousse/bits_of_static_binary_analysis/blob/bb23a406baa69ccec0a378ffe378837a417c4f8b/examples/01_command_line_injection_RDA_on_check.py#L28

**Comment by Pamplemousse** [comment]
AFAIR, this example does not make any use of any "research specific" code.
Also, as you suspect, `angr` is not stable, so it might very well be its API that changed for RDA.
